language: java

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
      - $HOME/.gradle/caches
      - $HOME/.gradle/wrapper

before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - sudo pip install html5validator

# sudo: false
sudo: required

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

# want more info when running tests and building manual
script:
  - ./gradlew assemble
  - ./gradlew --info check
  - ./gradlew --info manual
# TODO: this requires Java 8
#   - ./gradlew validate
  - ./gradlew verifyGoogleJavaFormat

after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 3
